import pkg from "../../package.json" with { type: "json" };

const INDENT = "  ";

const VERSION = (pkg as { version: string }).version;

/**
 * Options for {@link fileHeader}.
 */
export interface FileHeaderOptions {
    /** Theme metadata; if `meta.name` is non-empty, a `theme:` line is emitted. */
    meta?: { name?: string };
    /** Comment open delimiter (default `//`). */
    open?: string;
    /** Comment close delimiter (default empty for line comments). */
    close?: string;
}

/**
 * File header comment for all generated files. Defaults to JS-style `//`
 * line comments; pass alternate delimiters (e.g. `/*`, `*\/`) for CSS output.
 *
 * Emits up to two lines:
 *   1. `Auto-generated by theme-unify@<version> — do not edit`
 *   2. `theme: "<meta.name>"` (only when `meta.name` is non-empty)
 */
export function fileHeader(options: FileHeaderOptions = {}): string {
    const open = options.open ?? "//";
    const close = options.close ?? "";
    const wrap = (text: string): string =>
        close ? `${open} ${text} ${close}` : `${open} ${text}`;

    const lines: string[] = [
        wrap(`Auto-generated by theme-unify@${VERSION} — do not edit`),
    ];
    const name = options.meta?.name?.trim();
    if (name) {
        lines.push(wrap(`theme: ${JSON.stringify(name)}`));
    }
    return lines.join("\n") + "\n";
}

/**
 * Serialize a JavaScript value to TypeScript source code.
 */
export function serializeValue(value: unknown, depth: number = 0): string {
    if (value === null || value === undefined) {
        return String(value);
    }
    if (typeof value === "string") {
        return serializeString(value);
    }
    if (typeof value === "number" || typeof value === "boolean") {
        return String(value);
    }
    if (Array.isArray(value)) {
        if (value.length === 0) return "[]";
        const items = value.map(
            (item) => `${pad(depth + 1)}${serializeValue(item, depth + 1)}`,
        );
        return `[\n${items.join(",\n")},\n${pad(depth)}]`;
    }
    if (typeof value === "object") {
        return serializeObject(value as Record<string, unknown>, depth);
    }
    return String(value);
}

/**
 * Serialize a plain object to TypeScript source code.
 */
export function serializeObject(
    obj: Record<string, unknown>,
    depth: number = 0,
): string {
    const entries = Object.entries(obj);
    if (entries.length === 0) return "{}";

    const lines = entries.map(([key, val]) => {
        const safeKey = isValidIdentifier(key) ? key : serializeString(key);
        return `${pad(depth + 1)}${safeKey}: ${serializeValue(val, depth + 1)}`;
    });

    return `{\n${lines.join(",\n")},\n${pad(depth)}}`;
}

function serializeString(value: string): string {
    // Use single quotes, escape internal single quotes and backslashes
    const escaped = value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
    return `'${escaped}'`;
}

function isValidIdentifier(key: string): boolean {
    return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key);
}

function pad(depth: number): string {
    return INDENT.repeat(depth);
}

/**
 * Legacy semantic role names mapped to their canonical PrimeVue
 * severity vocabulary equivalent. Used by {@link canonicalizeSemanticRole}
 * so the styled preset and any downstream PT generator agree on the
 * key under which a scale lives in `semantic`.
 */
export const SEMANTIC_ROLE_ALIAS_MAP: Record<string, string> = {
    warning: "warn",
    error: "danger",
};

/**
 * Translate a semantic role name to its canonical PrimeVue severity
 * vocabulary equivalent. Unknown names pass through unchanged so
 * user-defined roles (e.g. `accent`) still survive into the preset.
 */
export function canonicalizeSemanticRole(role: string): string {
    return SEMANTIC_ROLE_ALIAS_MAP[role] ?? role;
}

/**
 * Convert a snake_case, camelCase, or PascalCase identifier to
 * kebab-case. Mirrors the conversion PrimeUix's `toVariables` applies
 * when materializing `--p-*` CSS variables, so the names theme-unify
 * embeds in `var()` references and UnoCSS export keys line up with the
 * variables PrimeVue actually emits at runtime.
 *
 * Example: `eggplantPurple` → `eggplant-purple`, `brand_color` →
 * `brand-color`. Already-lowercase strings (e.g. `slate`, `purple`)
 * pass through unchanged.
 */
export function toKebabCase(str: string): string {
    return str
        .replace(/_/g, "-")
        .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
        .toLowerCase();
}

import type { ColorScale, ColorStep } from "../types.js";
import { COLOR_STEPS } from "../types.js";

/**
 * Build a surface object with 0–950 keys from a color scale.
 * Shared between PrimeVue and UnoCSS generators so both use
 * the same source of truth for surface levels.
 *
 * `invert` reverses indices 50–950 (dark-mode convention where the darker
 * tones live at the low end of the scale).
 *
 * `surface[0]` is always `#ffffff` (Aura convention) — the brightest
 * possible surface, used by components for elements that should pop
 * against a dark background (switch handles, contrast text, etc.). The
 * `mode` parameter is accepted for API symmetry but does not affect
 * `surface[0]`.
 */
export function buildSurfaceObject(
    scale: ColorScale,
    invert: boolean,
    mode: "light" | "dark" = "light",
): Record<string, string> {
    void mode;
    const surface: Record<string, string> = {};
    const steps: ColorStep[] = [...COLOR_STEPS];

    surface["0"] = "#ffffff";

    if (invert) {
        const reversed = [...steps].reverse();
        for (let i = 0; i < steps.length; i++) {
            surface[String(steps[i])] = scale[reversed[i]];
        }
    } else {
        for (const step of steps) {
            surface[String(step)] = scale[step];
        }
    }

    return surface;
}
