const INDENT = "  ";

/**
 * File header comment for all generated files. Defaults to JS-style `//`
 * line comments; pass alternate delimiters (e.g. `/*`, `*\/`) for CSS output.
 */
export function fileHeader(open: string = "//", close: string = ""): string {
    const text = "Auto-generated by theme-unify — do not edit";
    if (close) {
        return `${open} ${text} ${close}\n`;
    }
    return `${open} ${text}\n`;
}

/**
 * Serialize a JavaScript value to TypeScript source code.
 */
export function serializeValue(value: unknown, depth: number = 0): string {
    if (value === null || value === undefined) {
        return String(value);
    }
    if (typeof value === "string") {
        return serializeString(value);
    }
    if (typeof value === "number" || typeof value === "boolean") {
        return String(value);
    }
    if (Array.isArray(value)) {
        if (value.length === 0) return "[]";
        const items = value.map(
            (item) => `${pad(depth + 1)}${serializeValue(item, depth + 1)}`,
        );
        return `[\n${items.join(",\n")},\n${pad(depth)}]`;
    }
    if (typeof value === "object") {
        return serializeObject(value as Record<string, unknown>, depth);
    }
    return String(value);
}

/**
 * Serialize a plain object to TypeScript source code.
 */
export function serializeObject(
    obj: Record<string, unknown>,
    depth: number = 0,
): string {
    const entries = Object.entries(obj);
    if (entries.length === 0) return "{}";

    const lines = entries.map(([key, val]) => {
        const safeKey = isValidIdentifier(key) ? key : serializeString(key);
        return `${pad(depth + 1)}${safeKey}: ${serializeValue(val, depth + 1)}`;
    });

    return `{\n${lines.join(",\n")},\n${pad(depth)}}`;
}

function serializeString(value: string): string {
    // Use single quotes, escape internal single quotes and backslashes
    const escaped = value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
    return `'${escaped}'`;
}

function isValidIdentifier(key: string): boolean {
    return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key);
}

function pad(depth: number): string {
    return INDENT.repeat(depth);
}

import type { ColorScale, ColorStep } from "../types.js";
import { COLOR_STEPS } from "../types.js";

/**
 * Build a surface object with 0–950 keys from a color scale.
 * Shared between PrimeVue and UnoCSS generators so both use
 * the same source of truth for surface levels.
 *
 * `invert` reverses indices 50–950 (dark-mode convention where the darker
 * tones live at the low end of the scale).
 *
 * `surface[0]` is always `#ffffff` (Aura convention) — the brightest
 * possible surface, used by components for elements that should pop
 * against a dark background (switch handles, contrast text, etc.). The
 * `mode` parameter is accepted for API symmetry but does not affect
 * `surface[0]`.
 */
export function buildSurfaceObject(
    scale: ColorScale,
    invert: boolean,
    mode: "light" | "dark" = "light",
): Record<string, string> {
    void mode;
    const surface: Record<string, string> = {};
    const steps: ColorStep[] = [...COLOR_STEPS];

    surface["0"] = "#ffffff";

    if (invert) {
        const reversed = [...steps].reverse();
        for (let i = 0; i < steps.length; i++) {
            surface[String(steps[i])] = scale[reversed[i]];
        }
    } else {
        for (const step of steps) {
            surface[String(step)] = scale[step];
        }
    }

    return surface;
}
