import { describe, it, expect } from "vitest";
import { generatePrimeVueBaseCss } from "../../src/generators/primevue.js";
import { resolveRefs } from "../../src/resolver.js";
import { validTokens } from "../fixtures/tokens.fixture.js";

describe("generatePrimeVueBaseCss", () => {
    it("returns null when neither base value is set", () => {
        const tokens = structuredClone(validTokens);
        tokens.primitive.typography = { fontFamily: "system-ui" };
        const resolved = resolveRefs(tokens);
        expect(generatePrimeVueBaseCss(resolved)).toBeNull();
    });

    it("returns null when typography is omitted entirely", () => {
        const tokens = structuredClone(validTokens);
        delete tokens.primitive.typography;
        const resolved = resolveRefs(tokens);
        expect(generatePrimeVueBaseCss(resolved)).toBeNull();
    });

    it("emits :root block with font-size, line-height, and font-family", () => {
        const resolved = resolveRefs(validTokens);
        const css = generatePrimeVueBaseCss(resolved);
        expect(css).not.toBeNull();
        expect(css!).toContain("/* Auto-generated by theme-unify");
        expect(css!).toContain(":root {");
        expect(css!).toContain("font-size: 1.125rem;");
        expect(css!).toContain("line-height: 1.6;");
        expect(css!).toContain("font-family: 'Ringside Narrow SSm A'");
    });

    it("excludes missing declarations", () => {
        const tokens = structuredClone(validTokens);
        tokens.primitive.typography = { baseFontSize: "1.25rem" };
        const resolved = resolveRefs(tokens);
        const css = generatePrimeVueBaseCss(resolved);
        expect(css).not.toBeNull();
        expect(css!).toContain("font-size: 1.25rem;");
        expect(css!).not.toContain("line-height:");
        expect(css!).not.toContain("font-family:");
    });
});
