import { describe, it, expect } from "vitest";
import {
    generatePrimeVuePT,
    buildPrimeVuePTObject,
} from "../../src/generators/primevue-pt.js";
import { resolveRefs } from "../../src/resolver.js";
import { validTokens } from "../fixtures/tokens.fixture.js";

describe("generatePrimeVuePT", () => {
    it("generates a file with the correct header and export", () => {
        const resolved = resolveRefs(validTokens);
        const output = generatePrimeVuePT(resolved);

        expect(output).toContain("// Auto-generated by theme-unify");
        expect(output).toContain("export const primevuePT =");
    });

    it("includes button component section", () => {
        const resolved = resolveRefs(validTokens);
        const output = generatePrimeVuePT(resolved);

        expect(output).toContain("button:");
        expect(output).toContain("root:");
        expect(output).toContain("label:");
    });

    it("includes all required component sections", () => {
        const resolved = resolveRefs(validTokens);
        const output = generatePrimeVuePT(resolved);

        const requiredComponents = [
            "button",
            "card",
            "inputtext",
            "textarea",
            "select",
            "datatable",
            "dialog",
            "drawer",
            "message",
            "toast",
            "tag",
            "badge",
            "panel",
            "accordion",
            "tabs",
            "menu",
            "menubar",
            "breadcrumb",
            "avatar",
            "progressbar",
        ];

        for (const comp of requiredComponents) {
            expect(output).toContain(`${comp}:`);
        }
    });

    it("uses beetroot scale classes for primary severity", () => {
        const resolved = resolveRefs(validTokens);
        const output = generatePrimeVuePT(resolved);

        // Primary is mapped to beetroot in the fixture
        expect(output).toContain("bg-beetroot-500");
        expect(output).toContain("bg-beetroot-600");
        expect(output).toContain("bg-beetroot-700");
    });

    it("uses kale scale classes for secondary severity", () => {
        const resolved = resolveRefs(validTokens);
        const output = generatePrimeVuePT(resolved);

        // Secondary/success are mapped to kale
        expect(output).toContain("bg-kale-500");
    });

    it("uses surface scale classes for card and layout components", () => {
        const resolved = resolveRefs(validTokens);
        const output = generatePrimeVuePT(resolved);

        // Surface is oatmeal in the fixture
        expect(output).toContain("oatmeal");
    });

    it("generates functions for dynamic severity variants (button root)", () => {
        const resolved = resolveRefs(validTokens);
        const output = generatePrimeVuePT(resolved);

        // Button root should be a function
        expect(output).toMatch(/root:.*function|root:.*=>/);
    });
});

describe("buildPrimeVuePTObject", () => {
    it("returns an object with component keys", () => {
        const resolved = resolveRefs(validTokens);
        const pt = buildPrimeVuePTObject(resolved);

        expect(pt).toHaveProperty("button");
        expect(pt).toHaveProperty("card");
        expect(pt).toHaveProperty("inputtext");
        expect(pt).toHaveProperty("dialog");
        expect(pt).toHaveProperty("message");
        expect(pt).toHaveProperty("toast");
    });

    it("button root is a function", () => {
        const resolved = resolveRefs(validTokens);
        const pt = buildPrimeVuePTObject(resolved) as Record<
            string,
            Record<string, unknown>
        >;

        expect(typeof pt.button.root).toBe("function");
    });

    it("button root function returns correct classes for primary severity", () => {
        const resolved = resolveRefs(validTokens);
        const pt = buildPrimeVuePTObject(resolved) as Record<
            string,
            Record<string, unknown>
        >;

        const rootFn = pt.button.root as (ctx: {
            props: Record<string, unknown>;
        }) => string;
        const classes = rootFn({ props: { severity: "primary" } });

        expect(classes).toContain("bg-beetroot-500");
        expect(classes).toContain("text-white");
    });

    it("button root function returns outlined variant classes", () => {
        const resolved = resolveRefs(validTokens);
        const pt = buildPrimeVuePTObject(resolved) as Record<
            string,
            Record<string, unknown>
        >;

        const rootFn = pt.button.root as (ctx: {
            props: Record<string, unknown>;
        }) => string;
        const classes = rootFn({
            props: { severity: "primary", variant: "outlined" },
        });

        expect(classes).toContain("bg-transparent");
        expect(classes).toContain("beetroot");
    });

    it("message root is a function that uses severity classes", () => {
        const resolved = resolveRefs(validTokens);
        const pt = buildPrimeVuePTObject(resolved) as Record<
            string,
            Record<string, unknown>
        >;

        const messagePT = pt.message as Record<string, unknown>;
        expect(typeof messagePT.root).toBe("function");

        const rootFn = messagePT.root as (ctx: {
            props: Record<string, unknown>;
        }) => string;
        const classes = rootFn({ props: { severity: "secondary" } });

        // Secondary maps to kale
        expect(classes).toContain("kale");
    });

    it("card root omits surface bg so the preset's surface.0 token wins", () => {
        const resolved = resolveRefs(validTokens);
        const pt = buildPrimeVuePTObject(resolved) as Record<
            string,
            Record<string, unknown>
        >;

        expect(typeof pt.card.root).toBe("string");
        // Background/text colour come from the PrimeVue preset (surface.0/surface.700)
        // so the PT must NOT pin a competing utility class.
        expect(pt.card.root as string).not.toContain("bg-");
        expect(pt.card.root as string).not.toContain("text-oatmeal");
        // Title/subtitle must also avoid pinning a surface text colour — they
        // inherit `color` from the card root, which the preset drives.
        expect(pt.card.title as string).not.toContain("oatmeal");
        expect(pt.card.title as string).not.toContain("chickpea");
        expect(pt.card.subtitle as string).not.toContain("oatmeal");
        expect(pt.card.subtitle as string).not.toContain("chickpea");
    });

    it("severity color mapping is correct for all roles", () => {
        const resolved = resolveRefs(validTokens);
        const pt = buildPrimeVuePTObject(resolved) as Record<
            string,
            Record<string, unknown>
        >;

        const rootFn = pt.button.root as (ctx: {
            props: Record<string, unknown>;
        }) => string;

        // danger maps to beetroot (error scale in fixture is beetroot)
        const dangerClasses = rootFn({ props: { severity: "danger" } });
        expect(dangerClasses).toContain("beetroot");

        // info maps to eggplant
        const infoClasses = rootFn({ props: { severity: "info" } });
        expect(infoClasses).toContain("eggplant");
    });
});
