import { describe, it, expect } from "vitest";
import { generatePrimeVue } from "../../src/generators/primevue.js";
import { resolveRefs } from "../../src/resolver.js";
import { validTokens } from "../fixtures/tokens.fixture.js";

describe("generatePrimeVue", () => {
  it("generates valid TypeScript with definePreset", () => {
    const resolved = resolveRefs(validTokens);
    const output = generatePrimeVue(resolved);

    expect(output).toContain("// Auto-generated by theme-unify");
    expect(output).toContain("import { definePreset } from '@primeuix/themes'");
    expect(output).toContain("import Aura from '@primeuix/themes/aura'");
    expect(output).toContain(
      "export const GeneratedPreset = definePreset(Aura,",
    );
  });

  it("maps primary color scale from semantic", () => {
    const resolved = resolveRefs(validTokens);
    const output = generatePrimeVue(resolved);

    // primary should have the beetroot scale
    expect(output).toContain("'50': '#FDF2F4'");
    expect(output).toContain("'500': '#D02B4B'");
    expect(output).toContain("'950': '#300A14'");
  });

  it("resolves refs in colorScheme to literal values", () => {
    const resolved = resolveRefs(validTokens);
    const output = generatePrimeVue(resolved);

    // light primary color should be resolved beetroot 500
    expect(output).toContain("color: '#D02B4B'");
    // dark primary color should be resolved beetroot 300
    expect(output).toContain("color: '#EF8E9E'");
  });

  it("includes focusRing with passthrough PrimeVue tokens", () => {
    const resolved = resolveRefs(validTokens);
    const output = generatePrimeVue(resolved);

    expect(output).toContain("width: '3px'");
    expect(output).toContain("color: '{primary.color}'");
  });

  it("resolves formField borderRadius ref", () => {
    const resolved = resolveRefs(validTokens);
    const output = generatePrimeVue(resolved);

    expect(output).toContain("borderRadius: '0.25rem'");
  });

  it("includes surface mapping with inversion for dark mode", () => {
    const resolved = resolveRefs(validTokens);
    const output = generatePrimeVue(resolved);

    // Surface should exist in colorScheme
    expect(output).toContain("surface");
  });

  it("passes through component overrides", () => {
    const resolved = resolveRefs(validTokens);
    const output = generatePrimeVue(resolved);

    expect(output).toContain("components");
    expect(output).toContain("card");
  });
});
