import { describe, it, expect } from "vitest";
import { generateUnoCSS } from "../../src/generators/unocss-theme.js";
import { resolveRefs } from "../../src/resolver.js";
import { validTokens } from "../fixtures/tokens.fixture.js";

describe("generateUnoCSS", () => {
  it("generates valid TypeScript exports", () => {
    const resolved = resolveRefs(validTokens);
    const output = generateUnoCSS(resolved);

    expect(output).toContain("// Auto-generated by theme-unify");
    expect(output).toContain("export const colors =");
    expect(output).toContain("export const borderRadius =");
    expect(output).toContain("export const boxShadow =");
    expect(output).toContain("export const fontFamily =");
    expect(output).toContain("export const fontWeight =");
  });

  it("includes all primitive color scales", () => {
    const resolved = resolveRefs(validTokens);
    const output = generateUnoCSS(resolved);

    expect(output).toContain("beetroot");
    expect(output).toContain("oatmeal");
    expect(output).toContain("chickpea");
    expect(output).toContain("kale");
    expect(output).toContain("carrot");
    expect(output).toContain("eggplant");
  });

  it("generates color aliases", () => {
    const resolved = resolveRefs(validTokens);
    const output = generateUnoCSS(resolved);

    // warm should be an alias for oatmeal
    expect(output).toContain("warm");
  });

  it("maps radii to borderRadius", () => {
    const resolved = resolveRefs(validTokens);
    const output = generateUnoCSS(resolved);

    expect(output).toContain("sm: '0.25rem'");
    expect(output).toContain("full: '9999px'");
  });

  it("maps shadows to boxShadow", () => {
    const resolved = resolveRefs(validTokens);
    const output = generateUnoCSS(resolved);

    expect(output).toContain("rgba(44, 24, 16, 0.06)");
  });

  it("maps typography.fontFamily to fontFamily.sans", () => {
    const resolved = resolveRefs(validTokens);
    const output = generateUnoCSS(resolved);

    expect(output).toContain("Ringside Narrow SSm A");
    expect(output).toContain("sans");
  });

  it("passes through fontWeight values", () => {
    const resolved = resolveRefs(validTokens);
    const output = generateUnoCSS(resolved);

    expect(output).toContain("normal: '400'");
    expect(output).toContain("bold: '700'");
  });
});
