import { describe, it, expect } from "vitest";
import { generateShortcuts } from "../../src/generators/unocss-shortcuts.js";
import { resolveRefs } from "../../src/resolver.js";
import { validTokens } from "../fixtures/tokens.fixture.js";
import type { TokenSchema } from "../../src/types.js";

describe("generateShortcuts", () => {
  it("generates valid TypeScript export", () => {
    const resolved = resolveRefs(validTokens);
    const output = generateShortcuts(resolved);

    expect(output).toContain("// Auto-generated by theme-unify");
    expect(output).toContain("export const shortcuts: Record<string, string>");
  });

  it("combines light and dark values", () => {
    const resolved = resolveRefs(validTokens);
    const output = generateShortcuts(resolved);

    expect(output).toContain(
      "'bg-page': 'bg-chickpea-50 dark:bg-chickpea-950'",
    );
    expect(output).toContain(
      "'bg-surface': 'bg-oatmeal-100 dark:bg-chickpea-900'",
    );
    expect(output).toContain("'text-body': 'text-warm-900 dark:text-warm-100'");
  });

  it("handles empty shortcuts", () => {
    const tokens: TokenSchema = {
      meta: {
        name: "Test",
        darkModeStrategy: "class",
        darkModeSelector: ".dark",
      },
      primitive: {
        colors: {
          red: {
            50: "#fef2f2",
            100: "#fee2e2",
            200: "#fecaca",
            300: "#fca5a5",
            400: "#f87171",
            500: "#ef4444",
            600: "#dc2626",
            700: "#b91c1c",
            800: "#991b1b",
            900: "#7f1d1d",
            950: "#450a0a",
          },
        },
      },
      unocss: {
        shortcuts: {},
      },
    };

    const resolved = resolveRefs(tokens);
    const output = generateShortcuts(resolved);

    expect(output).toContain(
      "export const shortcuts: Record<string, string> = {};",
    );
  });

  it("handles missing unocss section", () => {
    const tokens: TokenSchema = {
      meta: {
        name: "Test",
        darkModeStrategy: "class",
        darkModeSelector: ".dark",
      },
      primitive: {
        colors: {
          red: {
            50: "#fef2f2",
            100: "#fee2e2",
            200: "#fecaca",
            300: "#fca5a5",
            400: "#f87171",
            500: "#ef4444",
            600: "#dc2626",
            700: "#b91c1c",
            800: "#991b1b",
            900: "#7f1d1d",
            950: "#450a0a",
          },
        },
      },
    };

    const resolved = resolveRefs(tokens);
    const output = generateShortcuts(resolved);

    expect(output).toContain(
      "export const shortcuts: Record<string, string> = {};",
    );
  });
});
